async (page) => {
  const errors = [];
  const onError = error => errors.push(error.message);
  page.on('pageerror', onError);
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const read = () => page.evaluate(() => window.PowerAboveAll.getState());
  const clickRegion = async id => {
    await page.locator('#france-map').scrollIntoViewIfNeeded();
    const point = await page.evaluate(regionId => {
      const region = GameCore.regions.find(item => item.id === regionId);
      const point = new DOMPoint(region.x, region.y + 2).matrixTransform(document.querySelector('#france-map').getScreenCTM());
      return { x: point.x, y: point.y };
    }, id);
    await page.mouse.click(point.x, point.y);
  };
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.reload();
  await page.locator('#restart').click();
  await page.locator('#confirm-restart').click();
  assert((await read()).gold === 840, 'Fresh campaign treasury');
  await page.locator('#bread').click();
  let s = await read();
  assert(s.food === 320 && s.regions.ile.unrest === 33, 'Bread action changes food and unrest');
  assert(await page.locator('#bread').isDisabled(), 'Repeated order disabled');
  await page.locator('#save').click();
  await page.locator('#tax').click();
  assert((await read()).gold === 940, 'Tax adds treasury');
  await page.locator('#load').click();
  assert((await read()).gold === 840, 'Manual save restores previous state');
  await clickRegion('normandy');
  assert((await read()).selected === 'normandy', 'Map click selects Normandy');
  await page.locator('#march').click();
  assert((await read()).army === 'normandy', 'Army moves into adjacent quiet region');
  await page.locator('[data-tab=economy]').click();
  assert(await page.locator('.economy-table').isVisible(), 'Economy visible');
  await page.screenshot({ path: 'C:/Users/USER/projects/power-above-all/output/playwright/economy.png' });
  await page.locator('[data-tab=politics]').click();
  assert(await page.locator('.faction-card').count() === 3, 'Three political factions');
  await page.locator('#back-to-map').click();
  await page.locator('#end-turn').click();
  await page.locator('#end-turn').click();
  assert((await read()).week === 2 && (await read()).pendingEvent, 'Event appears');
  await page.locator('#end-turn').click();
  assert((await read()).week === 2, 'Unresolved event blocks turn');
  await page.locator('.event-choice').filter({ hasText: 'Открыть запасы' }).click();
  assert((await read()).pendingEvent === null, 'Event resolves');
  await page.locator('#end-turn').click();
  const beforeReload = JSON.stringify(await read());
  await page.reload();
  assert(JSON.stringify(await read()) === beforeReload, 'Autosave roundtrip exact');
  await page.locator('#restart').click();
  await page.locator('#confirm-restart').click();
  await clickRegion('champagne');
  await page.locator('#march').click();
  assert(await page.locator('#battle-dialog').isVisible(), 'Tactical dialog opens');
  await page.locator('#battle-pause').click();
  await page.screenshot({ path: 'C:/Users/USER/projects/power-above-all/output/playwright/battle.png' });
  await page.locator('#battle-retreat').click();
  await page.locator('#battle-result button').click();
  s = await read();
  assert(s.army === 'ile' && s.moves === 1 && s.troops < 1200 && s.resolvedBattles.length === 1, 'Retreat result applied to campaign');
  const afterRetreat = s.troops;
  await page.locator('#march').click();
  await page.locator('#battle-canvas').click({ position: { x: 415, y: 210 } });
  await page.locator('#battle-volley').click();
  await page.locator('#battle-result button').waitFor({ state: 'visible', timeout: 55000 });
  await page.locator('#battle-result button').click();
  s = await read();
  assert(s.moves === 0 && s.resolvedBattles.length === 2 && s.troops <= afterRetreat, 'Full battle returns result exactly once');
  assert(await page.locator('#battle-dialog').isHidden(), 'Battle dialog closes');
  assert(s.army === 'champagne', 'Player can win the demonstration battle');
  await page.locator('#restart').click();
  await page.locator('#confirm-restart').click();
  await page.screenshot({ path: 'C:/Users/USER/projects/power-above-all/output/playwright/desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile has no horizontal overflow');
  await page.screenshot({ path: 'C:/Users/USER/projects/power-above-all/output/playwright/mobile.png', fullPage: true });
  await clickRegion('poitou');
  assert((await read()).selected === 'poitou', 'Mobile map selection');
  await page.setViewportSize({ width: 1440, height: 960 });
  await clickRegion('ile');
  await page.locator('#help').click();
  assert(await page.locator('#info-dialog').isVisible(), 'Help opens');
  await page.locator('#info-dialog .wide').click();
  assert(errors.length === 0, errors.join('\n'));
  page.off('pageerror', onError);
  return { ok: true, checks: ['map', 'bread', 'tax', 'manual-save', 'autosave', 'march', 'economy', 'politics', 'event', 'retreat', 'full-battle', 'mobile', 'help'], battleSurvivors: s.troops, consoleErrors: errors };
}
